[package]
name = "aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "aggregator-meta"
path = "src/main.rs"

[dependencies.aggregator]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.1"
default-features = false
