[package]
name = "aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.aggregator]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.0"
default-features = false
